- name: Create AWS instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  remote_user: ubuntu
  roles:
    - create
    
- name: Install Bamboo
  hosts: webserver
  # connection: local
  gather_facts: False
  # remote_user: ubuntu
  roles:
    - bamboo